# Generated by Django 4.1.7 on 2023-02-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ropa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('descripcion', models.TextField(default='')),
                ('talla', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Ropa',
                'verbose_name_plural': 'Ropas',
                'ordering': ['nombre'],
            },
        ),
    ]
