# Generated by Django 4.1.7 on 2023-02-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_marca_producto_delete_ropa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='talla',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.AlterField(
            model_name='marca',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.CharField(choices=[('1', 'Small'), ('2', 'Medium'), ('3', 'Large'), ('4', 'Extra Large')], max_length=2),
        ),
    ]
